spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1989_Linzu
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.sincere: info
  file: log/blog-pro.log
server:
  port: 8080